# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('effectiveness_rating', models.IntegerField(blank=True, null=True, verbose_name='Effectiveness Rating')),
                ('size_rating', models.IntegerField(blank=True, null=True, verbose_name='Size Rating')),
                ('wordcount', models.IntegerField()),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('date_origin', models.DateField(blank=True, null=True, verbose_name='Est Date of Origin')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_formatlists', to='lists.Format')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Wordlist',
                'verbose_name_plural': 'Wordlists',
            },
        ),
        migrations.CreateModel(
            name='WordlistType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(default='#999999', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='wordlist',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_typelists', to='lists.WordlistType'),
        ),
    ]
