# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20160704_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
