# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20160704_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn_familylists', to='lists.Family'),
        ),
    ]
