# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lists.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lists', '0004_wordlist_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='sha1',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='sha1'),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='wordlist_file',
            field=models.FileField(blank=True,
                                   null=True, upload_to=lists.models.get_attachment_file_path,
                                   verbose_name='Wordlist File'),
            preserve_default=False,
        ),
    ]
